name: melos_demo

packages:
  - utility/**
  - features/**
  - "*"

scripts:
  test:selective_unit_test:
    run: melos exec --dir-exists="test" --fail-fast -- flutter test --no-pub --coverage
    description: Run Flutter tests for a specific package in this project.
    packageFilters:
      flutter: true
      dirExists: test
  test:
    run: melos run test:selective_unit_test --no-select
    description: Run All Flutter tests in this project.
  analyze:
    run: melos exec -- flutter analyze
    description: run `dart analyze` in all packages.
  gen_coverage: melos exec -- "\$MELOS_ROOT_PATH/combine_coverage.sh"
